'use strict';
const $=s=>document.querySelector(s);
const reduced=matchMedia('(prefers-reduced-motion: reduce)');
let savedTheme;try{savedTheme=localStorage.getItem('danny-theme')}catch{}
function theme(value){document.documentElement.dataset.theme=value;$('.theme-button').textContent=value==='dark'?'☼':'◐';$('.theme-button').setAttribute('aria-label',value==='dark'?'切換淺色模式':'切換深色模式');try{localStorage.setItem('danny-theme',value)}catch{}}
theme(savedTheme==='light'?'light':'dark');$('.theme-button').onclick=()=>theme(document.documentElement.dataset.theme==='dark'?'light':'dark');
function clock(){ $('#local-time').textContent=new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Taipei',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date())+' UTC+8'}clock();setInterval(clock,30000);
document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-filter]').forEach(t=>{t.classList.toggle('active',t===b);t.setAttribute('aria-pressed',String(t===b))});let count=0;document.querySelectorAll('.project').forEach(p=>{p.hidden=b.dataset.filter!=='all'&&p.dataset.category!==b.dataset.filter;if(!p.hidden)count++});$('.filter-count').textContent='SHOWING '+String(count).padStart(2,'0')+' PROJECTS'});
const entries={
corning:{title:'台灣康寧 / 產線數位化',body:`<p class="detail-metric">回溯時間 −99% · 實習競賽第二名</p><figure class="detail-figure detail-photo"><img src="assets/corning-interns.jpg?v=20260916b" alt="Corning Taiwan summer intern team photo" loading="lazy"><figcaption>2023 / CORNING TAIWAN · SUMMER INTERN TEAM</figcaption></figure><p>2023 年暑期實習，從零建置 Python / SQL 資料回溯介面，協助工程師快速定位產線問題。</p><h3>先理解現場怎麼找問題</h3><p>透過訪談釐清工程師查資料的路徑，再將分散的資料整理成可查詢的工具。隨使用回饋調整功能，減少資料整理與回溯的等待。</p><h3>讓工具成為實際成果</h3><p>專案回溯時間減少約 99%，並獲實習生競賽第二名。這段經驗也成為後續半導體資料系統工作的基礎。</p>`},
schedule:{title:'GAT × 強化學習智慧排程',body:`<p class="detail-metric">排程完成時間平均 −20%</p><figure class="detail-figure detail-diagram"><img src="assets/scheduling-research.svg?v=20260916b" alt="Scheduling model and benchmark diagram redrawn from master thesis" loading="lazy"><figcaption>MASTER THESIS / GAT + D3QN · STATIC ENVIRONMENT RESULTS</figcaption></figure><p>在陽明交通大學產學合作研究中，探索圖注意力網路與強化學習於產線排程的應用。</p><h3>和既有方法放在一起比較</h3><p>以規則式排程為對照，在多組測試情境中評估整體完成時間。研究實驗顯示平均縮短約 20%，並觀察動態條件下的穩定性。</p><h3>研究方法要回應現場限制</h3><p>在共同測試基準下，研究方法呈現平均 20% 的完成時間降幅，讓排程設計能用數據比較與驗證。</p>`},
ttt:{title:'TTT-Discover 用於 Alpha 挖掘',body:`<p class="detail-metric">個人實作與探索 · 單卡 TTT-Discover Alpha 挖掘</p><figure class="detail-figure detail-diagram"><img src="assets/resume/ttt-illustration.svg?v=20260916i" alt="TTT-Discover：單卡實作與實驗比較" loading="lazy"><figcaption>TTT-Discover：單卡實作與實驗比較</figcaption></figure><p>我把 TTT-Discover 的想法落在一張 RTX 4090 上：讓模型提出因子方向、生成程式、完成評估，再用結果更新 LoRA，進入下一輪探索。從程式設計到量測與驗證，這段個人實驗由我自行完成。</p><h3>把閉環搬到本地</h3><p>我以本地 Qwen2.5-Coder-7B-Instruct 產碼，沿用既有搜尋與評分框架，把註解掉的 train step 打開，接上後續 LoRA 更新。40 輪實驗的軌跡、日誌與候選結果都留有紀錄，讓研究可以從每一輪接續。</p><h3>一張卡，同時容納生成與更新</h3><p>生成和訓練若各自載入模型，記憶體預算會很快用完。我改用同一份 base 權重與 LoRA adapter，在階段間共用模型。4-bit 組態的 PyTorch allocated memory 峰值由 18.82 降至 13.63 GiB，減少 5.19 GiB，讓閉環有足夠空間持續運作。</p><h3>一次處理一批想法</h3><p>固定 16 個 idea，使用 vLLM 比較併發 1、4、8、16。產碼、驗證與評分的整批完成時間中位數由 39.52 秒降至 5.34 秒，在這段工作流程中加速約 7.4 倍。</p><h3>讓候選經得起檢查</h3><p>產碼後我檢查退化因子，再取 top-K 做 walk-forward 驗證，以樣本外 Sharpe 重新排序。每批有 7～8 個候選通過基本檢查且沒有退化。速度、記憶體與因子品質都分開留下實驗證據，幫助我決定下一步要優化什麼。</p><p class="detail-small">記憶體數字為 PyTorch allocated 峰值；7.4 倍對應固定 16 個 idea 的產碼、驗證與評分批次量測。</p>`},
agent:{title:'企業 AI Agent / 把模型接進工作流程',body:`<p>讓使用者描述需求，由模型撰寫 SQL，透過 MCP 資料庫工具執行，再根據實際查詢結果整理回覆。</p><p class="detail-metric">約 80 人次／日</p><figure class="detail-figure detail-diagram"><img src="assets/resume/agent-illustration.svg?v=20260916i" alt="企業 AI Agent：MCP 查詢與上線成果" loading="lazy"><figcaption>企業 AI Agent：MCP 查詢與上線成果</figcaption></figure><p>每日使用人次由系統直接統計，反映工具在實際工作流程中的使用。</p><h3>我的工作</h3><p>獨立完成架構設計、MCP 工具、資料整合與正式上線。模型推論使用閉源服務，工具端提供安全的資料庫操作。</p><h3>從對話到執行</h3><p>這個專案的重點，是把模型的回答接到真實資料與可執行工具。工程工作包含釐清資料需求、設計工具介面，以及讓各個部分在實際流程中連接起來。</p><p>這項正式上線的系統，完整展示我從資料工具、功能設計到交付的工程能力。</p>`},
worldquant:{title:'WorldQuant / 24/7 Agent Alpha 挖掘',body:`<p class="detail-metric">WorldQuant · 台灣區第四名</p><figure class="detail-figure detail-diagram"><img src="assets/resume/worldquant-illustration.svg?v=20260916i" alt="WorldQuant：24/7 Agent 與樹狀研究記憶" loading="lazy"><figcaption>WorldQuant：24/7 Agent 與樹狀研究記憶</figcaption></figure><p class="detail-metric">24,072 次回測 · 44 個已提交 Alpha</p><p>我建立一套 24/7 運作的 Agent Alpha 自動挖掘系統，把研究方向、候選產生、WorldQuant BRAIN 回測、結果檢查與下一輪決策接成連續流程。成果不只是一批因子，而是一套能持續研究、能留下記憶的系統。</p><h3>從假說開始，而不是只堆表達式</h3><p>每個研究方向先有一個經濟假說，說明訊號想捕捉什麼。Agent 再沿著方向提出變體、生成 Alpha expression，將候選送入 BRAIN 回測，取得績效與檢查結果。表達式、設定與結果連在一起保存，後續可以重看每一步為何成立。</p><h3>24/7 自動挖掘流程</h3><p>系統持續讀取前一輪狀態、挑選值得延伸的方向、產生候選、執行回測並寫回結果。需要等待的檢查會進入佇列，結果回來後再更新研究紀錄。這樣我能把人工時間用在設定研究問題與判斷方向，重複的生成和量測交給 Agent 接續執行。</p><h3>樹狀記憶：一個方向，一棵研究樹</h3><p>研究樹的 root 保存最初的假說；每個 node 保存它相對父節點改了什麼、為何改動、用了什麼 expression 與設定，以及回測後的 Sharpe、fitness、檢查和分支狀態。向下是加深同一個假說，橫向是測試不同變體。若某條分支走不通，系統仍保留紀錄，回到上層試新的 sibling，不會忘記已走過的路。</p><h3>讓結果回饋下一步</h3><p>我依回測與檢查結果，更新節點統計和每棵樹的最佳節點，再挑選下一個延伸點。研究不再靠零散筆記記住「哪個分數好」，而是能追溯從假說到候選、從候選到結果的完整脈絡。這套流程支撐了 24,072 次回測、44 個已提交 Alpha，並取得 WorldQuant 台灣區第四名。</p><p class="detail-small">此系統使用 Agent、工具與研究樹串接 BRAIN 平台；與 TTT-Discover 的模型訓練閉環為兩個獨立實作。</p>`},
wafer:{title:'Wafer Map / 回到數值本身',body:`<p>自動攔檢需要同時考慮該攔下的異常，以及不應誤攔的正常情況。我的工作從量測資料的表示方式開始。</p><p class="detail-metric">約 99% · NT$ 3 億</p><figure class="detail-figure detail-diagram"><img src="assets/resume/wafer-illustration.svg?v=20260916i" alt="Wafer Map：判讀方法與專案成果" loading="lazy"><figcaption>Wafer Map：判讀方法與專案成果</figcaption></figure><p>判讀表現約 99%，涵蓋應攔與應放行的情況；3 億元為產線工程師立案時預估的專案效益。</p><h3>重新檢查影像表示</h3><p>原始資料是數值型。如果先轉成圖片，就需要選擇顏色、尺度與轉換規則。當時沒有找到能公平保留原始特徵的方式，因此我回到數值特徵與製程知識，建立判讀流程。</p><h3>已落地與持續研究</h3><p>既有方案結合統計特徵與製程規則。目前持續研究隨機森林，在特徵工程與實驗之間調整，希望進一步提升判讀準確度。</p>`},
stdf:{title:'STDF / 讓新系統正確接手',body:`<p>以 Python 開源轉檔方案為基礎，客製化擷取所需欄位，再使用 Cython 改善大量資料的處理效能。</p><p class="detail-metric">原系統約 600 萬元／年</p><figure class="detail-figure detail-diagram"><img src="assets/resume/stdf-illustration.svg?v=20260916i" alt="STDF：缺失值、量測旗標與系統交付" loading="lazy"><figcaption>STDF：缺失值、量測旗標與系統交付</figcaption></figure><p>原系統年度維運成本約 600 萬元，提供系統替代決策的成本基準。</p><h3>看起來缺失，不一定真的缺失</h3><p>新舊系統比對時，一個沒有數值的欄位，可能代表缺失，也可能是量測故障。需要交叉檢查相關欄位與狀態 flag，才能確認真正的意思。</p><h3>把驗證放進交付</h3><p>在確認輸出差異與資料語意後，讓替代系統接手既有流程。截至這次專案整理，系統已上線半年，尚未需要修改或進版。</p><p>這個專案讓我學到，轉出資料只是第一步，後續系統能正確理解資料，才是完成交付。</p>`},
batch:{title:'併發增加，為什麼不會等比例變快？',body:`<p>同樣一批 16 個 idea，逐一處理用了 39.52 秒，併發 16 則是 5.34 秒。這讓等待時間明顯縮短，但沒有變成十六分之一。</p><h3>請求增加，硬體沒有增加</h3><p>所有請求仍共用同一張 GPU。批次處理有機會讓硬體更有效率地工作，但大家也同時分享算力和記憶體頻寬。</p><h3>等的是整批最後一個結果</h3><p>不同請求生成的程式長度不同；同一份回答也仍需逐步生成。除了產碼，整批計時還包含驗證、評分及初始化等工作。</p><h3>這次量到了什麼？</h3><p>併發 1、4、8、16 的完成時間中位數，分別為 39.52、11.76、7.95、5.34 秒。這證實了此工作負載的批次收益，但要定位算力、頻寬或排程的主要限制，仍需要額外 profiling。</p><p class="detail-small">2026-09-10 固定候選實驗整理。各組三次；使用相同 vLLM 引擎。未計入 idea 生成與模型訓練。</p>`},
representation:{title:'在選模型之前，先想想資料長什麼樣。',body:`<p>影像模型很有吸引力，但當手上的原始資料是數值，把它轉成圖片本身就是一連串設計決策。</p><h3>表示方式會影響看見的訊號</h3><p>顏色如何對應數值？尺度如何設定？數值之間的差異，轉換後還保留了多少？如果沒有先處理這些問題，模型學到的可能也包含轉換方式帶入的痕跡。</p><h3>從問題回到資料</h3><p>在 Wafer Map 專案中，我選擇回到數值特徵，結合製程知識與規則來設計判讀。這不表示影像方法一定不適合，而是當時需要先建立更合理的資料表示與驗證方式。</p><p>對我來說，選模型之前，先弄清楚模型實際看見什麼，是值得花時間的一步。</p>`},
trace:{title:'失敗的實驗，也值得留下一個位置。',body:`<p>當實驗越做越多，只記得「這個分數很好」還不夠。我更想知道，它為什麼變好，和上一版到底差在哪裡。</p><h3>把改動理由一起保存</h3><p>在 WorldQuant 的研究流程中，我將假說、實作與回測分開記錄，並保留父節點和延伸分支的關係。同一想法的不同參數組合，也能各自追溯。</p><h3>被淘汰的結果也是線索</h3><p>如果只保存成功的實驗，就很容易重走已經試過的路。記錄失敗、限制與篩選原因，可以讓下一次研究更清楚地知道要改什麼。</p><p>自動化不只是多跑幾次，也包括讓每次執行留下可以理解、可以接續的紀錄。</p>`}
};
let lastFocus=null;const dialog=$('#detail');function openEntry(key,kind){const e=entries[key];if(!e)return;lastFocus=document.activeElement;$('#detail-title').textContent=e.title;$('#detail-kind').textContent=kind;$('#detail-content').innerHTML=e.body;dialog.showModal();dialog.scrollTop=0;document.body.classList.add('modal-open');$('#close-detail').focus()}
document.querySelectorAll('[data-project]').forEach(b=>b.onclick=()=>openEntry(b.dataset.project,'PROJECT FILE / '+b.dataset.project.toUpperCase()));document.querySelectorAll('[data-note]').forEach(b=>b.onclick=()=>openEntry(b.dataset.note,'FIELD NOTE / RESEARCH'));
$('#close-detail').onclick=()=>dialog.close();dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});dialog.addEventListener('close',()=>{document.body.classList.remove('modal-open');lastFocus?.focus()});
$('#copy-email').onclick=async()=>{try{await navigator.clipboard.writeText('pangyenwang@gmail.com');$('#copy-status').textContent='已複製，期待你的來信。'}catch{$('#copy-status').textContent='請選取並複製：pangyenwang@gmail.com'}};

window.addEventListener('wafer-open',e=>openEntry(e.detail,'PROJECT FILE / '+String(e.detail).toUpperCase()));
