(() => {
  const key='danny_drinks_admin_token',repo='/repos/danny0926/danny0926.github.io';
  const dialog=document.createElement('dialog');dialog.className='drink-dialog';document.body.append(dialog);
  let current,trigger,token='',authorized=false,saving=false,editing=false,isNew=false;
  const el=(tag,text,cls)=>{const e=document.createElement(tag);if(text)e.textContent=text;if(cls)e.className=cls;return e;};
  function stored(){try{return localStorage.getItem(key)||sessionStorage.getItem(key)||'';}catch{return '';}}
  async function api(path,method='GET',body){const r=await fetch('https://api.github.com'+path,{method,cache:'no-store',headers:{Authorization:'Bearer '+token,Accept:'application/vnd.github+json','Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const v=await r.json();if(!r.ok)throw Error(r.status===401?'登入已過期，請重新登入。':r.status===403?'Token 沒有寫入權限。':r.status===409?'有其他更新，請重新開啟酒款後再試。':v.message||'連線失敗');return v;}
  const safe=v=>{try{return ['http:','https:'].includes(new URL(v,location.href).protocol);}catch{return false;}};
  async function publishImages(items,next,file,uploads){
    const head=await api(repo+'/git/ref/heads/main');
    const check=await api(repo+'/contents/data/drinks.json?ref='+head.object.sha);
    if(check.sha!==file.sha)throw Error('線上資料已更新，請重新整理後再試。');
    const base=await api(repo+'/git/commits/'+head.object.sha),tree=[];
    for(const upload of uploads){const blob=await api(repo+'/git/blobs','POST',{content:upload.base64,encoding:'base64'});tree.push({path:upload.path,mode:'100644',type:'blob',sha:blob.sha});}
    const data=await api(repo+'/git/blobs','POST',{content:JSON.stringify(items,null,2)+'\n',encoding:'utf-8'});
    tree.push({path:'data/drinks.json',mode:'100644',type:'blob',sha:data.sha});
    const result=await api(repo+'/git/trees','POST',{base_tree:base.tree.sha,tree});
    const commit=await api(repo+'/git/commits','POST',{message:'Update drink notes and images: '+next.name,tree:result.sha,parents:[head.object.sha]});
    await api(repo+'/git/refs/heads/main','PATCH',{sha:commit.sha,force:false});
  }
  function render(){
    dialog.replaceChildren();const header=el('header','','detail-header'),title=el('h2',current.name),edit=el('button',authorized?'編輯這款酒':'管理員登入'),close=el('button','✕');close.setAttribute('aria-label','關閉酒款視窗');close.onclick=()=>{if(!saving&&(!editing||confirm('放棄尚未儲存的編輯？')))dialog.close();};edit.hidden=!authorized;edit.onclick=()=>{if(authorized)editor();};header.append(title,edit,close);dialog.append(header);
    const top=el('div','','detail-top'),photo=el('div','','detail-photo'),img=el('img');if(safe(current.image)){img.src=current.image;img.alt=current.name;photo.append(img);}const info=el('section','','detail-info');info.append(el('h3',current.informationLabel||'OFFICIAL NOTES / 官方資訊'),el('p',current.description),el('p',current.spec,'detail-muted'));
    if(current.officialSummary?.trim()){const list=el('ul');current.officialSummary.split('\n').filter(x=>x.trim()).forEach(t=>list.append(el('li',t)));info.append(list);}else info.append(el('p','官方品飲摘要尚未整理。','detail-muted'));
    const source=current.officialSource||current.source;if(source&&safe(source)){const a=el('a','原文與圖片來源 ↗');a.href=source;a.target='_blank';a.rel='noopener noreferrer';info.append(a);}top.append(photo,info);
    const bottom=el('div','','detail-bottom'),note=el('section','','detail-note'),radar=el('section','','detail-radar');note.append(el('h3','PERSONAL NOTE / 我的筆記'));window.drinkNoteEditor.render(note,current);radar.append(el('h3','MY IMPRESSION / 我的品飲感受'));const axes=window.drinkAxes[current.category];if(Array.isArray(current.scores)&&current.scores.length===axes.length&&current.scores.every(v=>Number.isFinite(v)&&v>=0&&v<=5)){radar.append(window.renderDrinkRadar(current.scores,axes));radar.append(el('p','0–5 表示感受強度，餘韻表示長度；不是品質評分。','detail-muted'));}else radar.append(el('p','尚未填寫品飲分數。','detail-muted'));bottom.append(note,radar);dialog.append(top,bottom,el('p','','detail-status'));
  }
  function status(t){dialog.querySelector('.detail-status').textContent=t;}
  function login(){if(dialog.querySelector('.detail-form'))return;const form=el('form','','detail-form'),label=el('label','GitHub Token'),input=el('input');input.type='password';input.autocomplete='off';input.required=true;label.append(input);const remember=el('input');remember.type='checkbox';const check=el('label');check.append(remember,document.createTextNode(' 記住這台裝置'));const button=el('button','登入並編輯');form.append(label,check,el('p','使用只授權網站儲存庫 Contents：Read and write 的 Token。','detail-muted'),button);dialog.insertBefore(form,dialog.querySelector('.detail-status'));form.onsubmit=async e=>{e.preventDefault();button.disabled=true;try{token=input.value.trim();const user=await api('/user');if(user.login.toLowerCase()!=='danny0926')throw Error('請使用 danny0926 帳號。');authorized=true;try{(remember.checked?localStorage:sessionStorage).setItem(key,token);}catch{}render();editor();}catch(e){status(e.message);}finally{button.disabled=false;}};}
  function editor(){if(dialog.querySelector('.detail-form'))return;editing=true;let uploaded=null;const form=el('form','','detail-form');const fields={image:'酒瓶圖片網址或站內路徑',source:'圖片來源網址',name:'酒款名稱',description:'基本介紹',spec:'容量／濃度',officialSummary:'官方原文摘要（一行一點，請勿填寫未確認內容）',officialSource:'官方文字來源網址',notes:'我的品飲筆記'};
    const categoryLabel=el('label','酒類分類'),category=el('select');category.name='category';Object.entries({sake:'清酒',beer:'啤酒',whisky:'威士忌',baijiu:'白酒',awamori:'燒酎・泡盛'}).forEach(([v,t])=>{const o=el('option',t);o.value=v;category.append(o);});category.value=current.category;categoryLabel.append(category);form.append(categoryLabel);Object.entries(fields).forEach(([key,label])=>{const l=el('label',label),i=el(key==='notes'||key==='officialSummary'?'textarea':'input');i.name=key;i.value=current[key]||'';if(i.tagName==='TEXTAREA')i.rows=5;if(key==='name')i.required=true;if(key==='officialSource')i.type='url';l.append(i);form.append(l);});const uploadLabel=el('label','上傳酒瓶圖片（最大 5 MB）'),upload=el('input');upload.type='file';upload.accept='image/jpeg,image/png,image/webp';uploadLabel.append(upload);form.append(uploadLabel);upload.onchange=()=>{const f=upload.files[0];if(!f)return;if(!['image/jpeg','image/png','image/webp'].includes(f.type)||f.size>5*1024*1024){status('請選擇 5 MB 以下的 JPEG、PNG 或 WebP。');return;}const reader=new FileReader();reader.onload=()=>{const path='assets/drinks/uploads/'+crypto.randomUUID()+'.'+({'image/jpeg':'jpg','image/png':'png','image/webp':'webp'}[f.type]);uploaded={path,base64:reader.result.split(',')[1]};form.elements.image.value=path;status('圖片已加入，儲存時一起發布。');};reader.readAsDataURL(f);};const notePhotos=window.drinkNoteEditor.editor(form.elements.notes,current,status);const check=el('label'),enabled=el('input');enabled.type='checkbox';enabled.checked=Array.isArray(current.scores);check.append(enabled,document.createTextNode(' 顯示雷達圖'));form.append(check);const scores=el('div','','detail-scores');function scoreInputs(values){scores.replaceChildren();window.drinkAxes[category.value].forEach((a,i)=>{const label=el('label',a),input=el('input');input.type='number';input.min=0;input.max=5;input.step=1;input.value=values?.[i]??0;input.dataset.score=i;label.append(input);scores.append(label);});}scoreInputs(current.scores);category.onchange=()=>scoreInputs(null);scores.hidden=!enabled.checked;enabled.onchange=()=>scores.hidden=!enabled.checked;form.append(scores);const submit=el('button','儲存並發布'),cancel=el('button','取消編輯');cancel.type='button';cancel.onclick=()=>{editing=false;render();};form.append(submit,cancel);dialog.insertBefore(form,dialog.querySelector('.detail-status'));form.scrollIntoView({behavior:'smooth',block:'start'});
    form.onsubmit=async e=>{e.preventDefault();if(saving)return;if(notePhotos.pending){status('圖片正在讀取，請稍候再儲存。');return;}saving=true;form.inert=true;submit.disabled=true;status('正在儲存到 GitHub…');try{const file=await api(repo+'/contents/data/drinks.json?ref=main');const items=JSON.parse(new TextDecoder().decode(Uint8Array.from(atob(file.content.replace(/\s/g,'')),c=>c.charCodeAt(0))));const index=items.findIndex(x=>x.id===current.id);if(index<0&&!isNew)throw Error('酒款已被刪除，請重新整理。');if(index>=0&&JSON.stringify(items[index])!==JSON.stringify(current))throw Error('此酒款已有新版本。請先複製筆記，再重新整理，避免覆蓋。');const next={...current,category:category.value};Object.keys(fields).filter(k=>k!=='notes').forEach(k=>next[k]=form.elements[k].value.trim());const noteDraft=notePhotos.snapshot();next.notesHtml=noteDraft.html;next.notes=noteDraft.text;delete next.noteImages;next.scores=enabled.checked?[...scores.querySelectorAll('input')].map(x=>Number(x.value)):null;if(index<0)items.push(next);else items[index]=next;const bytes=new TextEncoder().encode(JSON.stringify(items,null,2)+'\n');let binary='';bytes.forEach(b=>binary+=String.fromCharCode(b));const imageUploads=noteDraft.uploads;if(uploaded&&next.image===uploaded.path)imageUploads.push(uploaded);if(imageUploads.length)await publishImages(items,next,file,imageUploads);else await api(repo+'/contents/data/drinks.json','PUT',{message:'Update drink notes: '+next.name,content:btoa(binary),sha:file.sha,branch:'main'});current=next;isNew=false;window.drinksCollection=items;window.renderDrinks?.(items);editing=false;render();status('已儲存，GitHub Pages 正在部署更新。');}catch(e){status(e.message);}finally{saving=false;form.inert=false;submit.disabled=false;}};
  }
  async function open(id,button){const item=window.drinksCollection?.find(x=>x.id===id);if(!item)return;current=item;trigger=button;editing=false;isNew=false;token=stored();authorized=false;render();dialog.showModal();if(token){try{const u=await api('/user');if(current.id===id&&dialog.open){authorized=u.login.toLowerCase()==='danny0926';render();}}catch{/* Leave the public view usable when a saved token has expired. */}}}
  async function managementToolbar(){
    token=stored();if(!token)return;
    try{const user=await api('/user');if(user.login.toLowerCase()!=='danny0926')return;authorized=true;
      const bar=el('div','','drinks-management');bar.append(el('span','管理模式 · DANNY'));
      const add=el('button','＋ 新增酒款'),logout=el('button','登出管理模式');
      add.onclick=()=>{current={id:crypto.randomUUID(),category:'sake',name:'新的酒款',description:'',spec:'',image:'',source:'',officialSummary:'',officialSource:'',notes:'',scores:null};isNew=true;editing=false;trigger=add;render();dialog.showModal();editor();};
      logout.onclick=()=>{try{localStorage.removeItem(key);sessionStorage.removeItem(key);}catch{}token='';authorized=false;bar.remove();if(dialog.open)render();};bar.append(add,logout);document.querySelector('.drink-categories').after(bar);
    }catch{/* Keep the public interface when credentials have expired. */}
  }
  managementToolbar();
  document.addEventListener('click',e=>{const card=e.target.closest('[data-drink-id]');if(card&&!e.target.closest('a'))open(card.dataset.drinkId,card);});
  document.addEventListener('keydown',e=>{const card=e.target.closest('[data-drink-id]');if(card&&e.target===card&&(e.key==='Enter'||e.key===' ')){e.preventDefault();open(card.dataset.drinkId,card);}});
  dialog.addEventListener('cancel',e=>{if(saving||editing&&!confirm('放棄尚未儲存的編輯？'))e.preventDefault();});dialog.addEventListener('close',()=>trigger?.focus());
})();
