import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
export const dieEntries=[
 {id:'drinks',xy:[2,3],label:['DRINKS'],name:'我的酒櫃',type:'drinks',href:'drinks.html',note:'清酒、泡盛與白酒，收藏喝過的酒，也留下一杯背後的故事。',metric:'12 款收藏 / 飲酒筆記'},
 {id:'wafer',xy:[-1,-2],label:['晶圓','攔檢'],name:'Wafer Map 自動攔檢',type:'work',note:'以原始數值與製程規則建立已上線的判讀方案，並持續優化隨機森林特徵工程。',metric:'約 99% 判讀表現'},
 {id:'stdf',xy:[-3,0],label:['STDF'],name:'STDF 轉檔系統',type:'work',note:'客製化欄位、以 Cython 加速，並透過量測 flag 驗證資料，讓新系統正確接手。',metric:'穩定上線半年'},
 {id:'agent',xy:[-1,1],label:['AI','Agent'],name:'企業 AI Agent',type:'work',note:'獨立完成架構、MCP 資料庫工具、資料整合與正式上線，接進每日工作流程。',metric:'約 80 使用人次／日'},
 {id:'ttt',xy:[1,2],label:['TTT','Alpha'],name:'TTT-Discover 用於 Alpha 挖掘',type:'work',note:'在單卡上實作 TTT-Discover 因子挖掘閉環，完成共享權重、LoRA 更新與本地批次產碼評估。',metric:'批次產碼評估加速 7.4×'},
 {id:'worldquant',xy:[-2,-1],label:['WQ','因子'],name:'WorldQuant',type:'work',note:'以 Agent 串接 Alpha 研究、回測與結果紀錄，保留每個假說與延伸分支。',metric:'台灣區第四名 · 24,072 次回測'},
 {id:'corning',xy:[-1,3],label:['康寧','資料'],name:'台灣康寧 / 產線數位化',type:'work',note:'訪談工程師需求並建置 Python / SQL 資料回溯工具，協助現場快速定位問題。',metric:'回溯時間減少約 99% · 實習競賽第二名'},
 {id:'schedule',xy:[2,-2],label:['GAT','排程'],name:'GAT 智慧排程',type:'work',note:'在陽明交大產學研究中，以共同測試基準驗證圖注意力網路與強化學習排程。',metric:'研究情境中，完成時間平均減少約 20%'},
 {id:'voice',xy:[1,0],label:['夏吉'],name:'夏吉ゆうこ',type:'voice',href:'voice.html',note:'從千砂，到 THE FIRST TAKE。喜歡她在鏡頭前的自由，也喜歡安靜的那一面。',metric:'我的聲優手帖 / 角色、音樂與番組'},
 {id:'music',xy:[3,1],label:['MUSIC'],name:'J-POP 唱片架',type:'music',href:'jpop.html',note:'收藏陪我考研的〈Pieces〉，也替 Arika〈blan_〉的故事留下一頁。',metric:'我的聆聽筆記'},
 {id:'resume',xy:[0,-3],label:['履歷'],name:'王邦彥 / 完整履歷',type:'person',href:'resume.html',note:'資深軟體工程師。從成功大學數學系、陽明交大數據科學與工程，到半導體系統與 AI。',metric:'經歷、專案、競賽與專業技能'},
 {id:'notes',xy:[-3,2],label:['筆記'],name:'研究筆記',type:'person',href:'journal.html',note:'記錄資料表示、併發與實驗流程中的具體觀察，讓研究可以接續。',metric:'FIELD NOTES / 三篇實作紀錄'},
];
const named=Object.fromEntries(dieEntries.map(d=>[d.xy.join(','),d]));
function openDie(d){location.href=d.href||'projects.html#'+d.id}
export function WaferHome(){const [active,setActive]=useState(dieEntries.find(d=>d.id==='voice'));const cells=[];for(let y=-4;y<=4;y++)for(let x=-4;x<=4;x++)if(x*x+y*y<=17)cells.push([x,y]);return <div className="wafer-layout"><div className="wafer-person"><span className="wafer-lot">LOT / DANNY WANG / TAIWAN</span><div className="wafer-name"><h1>王邦彥<span>Danny Wang</span></h1><img src="assets/portrait.jpg?v=20260916b" alt="王邦彥彩色照片"/></div><p className="wafer-role">資深軟體工程師 · 世界先進</p><p className="wafer-intro">我在晶圓廠寫軟體。做產線系統、AI Agent，也在一張顯示卡上研究語言模型。</p><p className="wafer-explainer">點一顆有顏色的 die，看看裡面的故事。</p><div className={'die-readout '+active.type}><span className="die-address">DIE ({active.xy[0]}, {active.xy[1]}) / {active.type.toUpperCase()}</span><h2>{active.name}</h2><p>{active.note}</p><strong>{active.metric}</strong><button onClick={()=>openDie(active)}>{active.href?'前往這一頁':'打開專案紀錄'} <span>↗</span></button></div></div><div className="wafer-map"><div className="map-heading"><span>WAFER 01 / PERSONAL MAP</span><span>12 ACTIVE DIES</span></div><svg className="wafer-svg" viewBox="-560 -560 1120 1120" aria-label="晶圓導覽：青綠色是專案，粉色是夏吉，琥珀色是音樂，藍色是履歷與筆記"><circle r="525" className="wafer-ring"/><circle r="508" className="wafer-inner-ring"/><path d="M -22 525 L 0 503 L 22 525" className="wafer-notch"/>{cells.map(([x,y])=>{const d=named[x+','+y];return d?<g key={d.id} className={'nav-die '+d.type+(active.id===d.id?' is-active':'')} role="button" tabIndex="0" aria-label={d.name+'，'+d.metric} onPointerEnter={()=>setActive(d)} onFocus={()=>setActive(d)} onClick={()=>openDie(d)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openDie(d)}}}><title>{d.name}</title><rect x={x*100-42} y={y*100-42} width="84" height="84" rx="5"/><text x={x*100} y={y*100+7} textAnchor="middle">{d.label.length===1?<tspan x={x*100} dy="0">{d.label[0]}</tspan>:<><tspan x={x*100} dy="-11">{d.label[0]}</tspan><tspan className="die-sub" x={x*100} dy="24">{d.label[1]}</tspan></>}</text>{d.id==='voice'&&<rect className="voice-marker" x={x*100-49} y={y*100-49} width="98" height="98" rx="8"/>}</g>:<rect key={x+','+y} className="empty-die" x={x*100-42} y={y*100-42} width="84" height="84" rx="5"/>})}<path className="voice-leader" d="M 154 0 H 335 L 425 -95 H 515"/><text className="voice-map-label" x="370" y="-115">夏吉ゆうこ</text></svg><div className="map-legend"><a href="drinks.html"><i className="drinks"/>Drinks</a><span><i className="work"/>工程專案</span><a href="voice.html"><i className="voice"/>夏吉ゆうこ ↗</a><a href="jpop.html"><i className="music"/>Music</a><a href="resume.html"><i className="person"/>關於我</a></div><div className="map-caption"><span>色塊是入口，灰色是留白。</span><a href="projects.html">瀏覽全部專案 ↗</a></div></div></div>}
if(typeof document!=='undefined'){const node=document.getElementById('wafer-home');if(node)createRoot(node).render(<WaferHome/>)}
