(() => {
  const $=s=>document.querySelector(s),repo='/repos/danny0926/danny0926.github.io';
  let token='',items=[],revision='',selected='',dirty=false,busy=false;
  const uploads=new Map(),form=$('#form');
  const message=t=>{$('#status').textContent=t;};
  async function api(path,method='GET',body){const r=await fetch('https://api.github.com'+path,{method,cache:'no-store',headers:{Authorization:'Bearer '+token,Accept:'application/vnd.github+json','Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const data=await r.json();if(!r.ok)throw Error(r.status===401?'Token 無效或已過期。':r.status===403?'權限不足，請確認 Contents：Read and write。':r.status===422||r.status===409?'發布衝突，請匯出草稿，再重新登入讀取最新版。':data.message||'GitHub 連線失敗');return data;}
  function refresh(){const sel=$('#collection');sel.replaceChildren();items.forEach(item=>{const o=document.createElement('option');o.value=item.id;o.textContent=item.name;sel.append(o);});sel.value=selected;}
  function drawScores(values){const box=$('#scores');box.replaceChildren();const axes=window.drinkAxes[form.elements.category.value];axes.forEach((a,i)=>{const label=document.createElement('label');label.textContent=a;const input=document.createElement('input');input.type='number';input.min=0;input.max=5;input.step=1;input.value=values?.[i]??0;input.dataset.score=i;label.append(input);box.append(label);});box.hidden=!$('#enable-radar').checked;}
  function preview(){const path=form.elements.image.value;const img=$('#preview');let url;try{url=new URL(path,location.origin+'/');}catch{}if(path&&url&&['http:','https:'].includes(url.protocol)){img.src=uploads.get(path)?.preview||url.href;img.hidden=false;}else img.hidden=true;}
  function load(id){selected=id;const item=items.find(x=>x.id===id);if(!item)return;['category','name','description','spec','image','source','notes'].forEach(k=>{form.elements[k].value=item[k]||'';});$('#enable-radar').checked=Array.isArray(item.scores);drawScores(item.scores);$('#upload').value='';refresh();preview();}
  function save(){if(!form.reportValidity())return false;const item=items.find(x=>x.id===selected);if(!item)return false;for(const k of ['category','name','description','spec','image','source','notes'])item[k]=form.elements[k].value.trim();item.scores=$('#enable-radar').checked?[...document.querySelectorAll('#scores input')].map(x=>Number(x.value)):null;if(item.scores?.some(v=>!Number.isInteger(v)||v<0||v>5)){message('分數請填入 0～5 的整數。');return false;}dirty=true;refresh();return true;}
  form.addEventListener('submit',e=>{e.preventDefault();if(save())message('已儲存到草稿，尚未發布。');});
  $('#collection').onchange=e=>{const next=e.target.value;if(save())load(next);else e.target.value=selected;};
  form.elements.category.onchange=()=>drawScores(null);
  $('#enable-radar').onchange=()=>{$('#scores').hidden=!$('#enable-radar').checked;};
  form.elements.image.onchange=preview;
  form.addEventListener('input',()=>{dirty=true;});
  $('#connect').onclick=async()=>{if(busy)return;busy=true;$('#connect').disabled=true;try{token=$('#token').value.trim();$('#token').value='';const user=await api('/user');if(user.login.toLowerCase()!=='danny0926')throw Error('請使用 danny0926 的 GitHub 帳號。');const head=await api(repo+'/git/ref/heads/main');revision=head.object.sha;const file=await api(repo+'/contents/data/drinks.json?ref='+revision);items=JSON.parse(new TextDecoder().decode(Uint8Array.from(atob(file.content.replace(/\s/g,'')),x=>x.charCodeAt(0))));$('#login').hidden=true;$('#editor').hidden=false;load(items[0]?.id);dirty=false;message('已連接 danny0926，載入 '+items.length+' 款酒。');}catch(e){token='';message(e.message);}finally{busy=false;$('#connect').disabled=false;}};
  $('#logout').onclick=()=>{if(dirty&&!confirm('草稿尚未發布，確定登出？'))return;token='';items=[];uploads.clear();dirty=false;$('#editor').hidden=true;$('#login').hidden=false;message('已登出，Token 已清除。');};
  $('#new').onclick=()=>{if(selected&&!save())return;const item={id:crypto.randomUUID(),category:'sake',name:'新的酒款',description:'',spec:'',image:'',source:'',notes:'',scores:null};items.push(item);load(item.id);dirty=true;};
  $('#delete').onclick=()=>{if(!confirm('確定從草稿刪除這款酒？發布後才會更新網站。'))return;items=items.filter(x=>x.id!==selected);selected=items[0]?.id||'';refresh();if(selected)load(selected);else form.reset();dirty=true;};
  $('#upload').onchange=async()=>{const file=$('#upload').files[0];if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5*1024*1024){message('請選擇 5 MB 以下的 JPEG、PNG 或 WebP。');return;}try{const base64=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result.split(',')[1]);reader.onerror=reject;reader.readAsDataURL(file);});const path='assets/drinks/uploads/'+crypto.randomUUID()+'.'+({'image/jpeg':'jpg','image/png':'png','image/webp':'webp'}[file.type]);uploads.set(path,{base64,preview:URL.createObjectURL(file)});form.elements.image.value=path;preview();dirty=true;message('圖片已加入草稿，發布時會一起上傳。');}catch{message('圖片讀取失敗。');}};
  $('#export').onclick=()=>{if(selected&&!save())return;const url=URL.createObjectURL(new Blob([JSON.stringify(items,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='drinks-draft.json';a.click();URL.revokeObjectURL(url);message('已匯出文字與分數；尚未發布的上傳圖片請另外保留原檔。');};
  $('#publish').onclick=async()=>{if(busy||selected&&!save())return;if(!confirm('發布整份酒櫃到公開網站？'))return;busy=true;$('#editor').inert=true;message('正在發布…');try{const head=await api(repo+'/git/ref/heads/main');if(head.object.sha!==revision)throw Error('線上已有新版本。請匯出草稿，再重新登入讀取最新版，避免覆蓋。');const commit=await api(repo+'/git/commits/'+revision);const tree=[];for(const [path,file] of uploads){if(!items.some(x=>x.image===path))continue;const blob=await api(repo+'/git/blobs','POST',{content:file.base64,encoding:'base64'});tree.push({path,mode:'100644',type:'blob',sha:blob.sha});}const blob=await api(repo+'/git/blobs','POST',{content:JSON.stringify(items,null,2)+'\n',encoding:'utf-8'});tree.push({path:'data/drinks.json',mode:'100644',type:'blob',sha:blob.sha});const newTree=await api(repo+'/git/trees','POST',{base_tree:commit.tree.sha,tree});const next=await api(repo+'/git/commits','POST',{message:'Update drinks collection from admin',tree:newTree.sha,parents:[revision]});await api(repo+'/git/refs/heads/main','PATCH',{sha:next.sha,force:false});revision=next.sha;uploads.clear();dirty=false;message('已發布到 GitHub（'+next.sha.slice(0,7)+'）。網站正在自動部署，通常稍等片刻即可看到更新。');}catch(e){message(e.message);}finally{busy=false;$('#editor').inert=false;}};
  window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
})();
